version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: my-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    depends_on:
      - postgres
    networks:
      - my-network

  grafana:
    image: grafana/grafana
    container_name: my-grafana
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - my-network

volumes:
  postgres-data:
  jenkins-data:
  grafana-data:

networks:
  my-network:
    driver: bridge
